deployment:
  tasks:
    - export DEPLOYPATH=/home/gstgrp/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets index.html send_email.php favicon.png placeholder.svg robots.txt .htaccess $DEPLOYPATH
